### ISSUE TITLE
虚拟串口乱码

### ISSUE THREAD

**Issue by Rbb666** [XIVN1987/DAPLink#1]
你好，我使用这个固件发现用默认的串口波特率会乱码，调试的时候发现也是正常收到数据了，到了USB输出那里就出现问题了，请问该怎么解决？

**Comment by XIVN1987** [comment]
AT32F425版的USB转串口还没调好，，还在调。。

**Comment by Rbb666** [comment]
> AT32F425版的USB转串口还没调好，，还在调。。

好的，谢谢，持续关注

**Comment by XIVN1987** [comment]
问题已解决。。
