### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by LLLCCCWWW1** [XIVN1987/DAPLink#11]
请问大佬，为什么用CH32V203方案的那个link，给同一个芯片在同一台电脑下载过后，换到其他电脑再下载就会报错，然后拿回自己的电脑下载也会报错
错误是cannot access memory (@ 0xe000edf0 read acc size 4 byte)

**Comment by XIVN1987** [comment]
用别的 link（比如J-link）给同一个芯片下载相同的程序有问题吗？？

**Comment by LLLCCCWWW1** [comment]
用其他的可以，用ch32这个方案，出现问题后必须手动给boot0拉高上电才能下，但是后续还是会出现这个问题

**Comment by LLLCCCWWW1** [comment]
佬 找到问题了 代码进休眠模式下载不进去
