### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by zbs2004** [XIVN1987/DAPLink#12]
首先，感谢您的ch32v203项目，使我完成了板载daplink的设计；
但我们的项目需要调试多个串口，希望您的固件能提供更多cdc_uart串口通信接口

**Comment by XIVN1987** [comment]
之前搞过 CDC 多串口，，在电脑上自动分配串口号 COMx、COMy，，没法简单的区分出它们分别对应硬件上的哪个串口，，造成使用麻烦，，所以不建议使用 CDC 多串口。。
