### ISSUE TITLE
最近更新的V203可以用了吗

### ISSUE THREAD

**Issue by AITCK** [XIVN1987/DAPLink#2]
大佬，最近更新的V203可以用了吗，有购买v203的芯片渠道吗

**Comment by XIVN1987** [comment]
可以用，，芯片在淘宝买的。。

**Comment by AITCK** [comment]
我编译了CH32V203的工程，编译出来的HEX大小50KB，是不是要用CH32V203F8P6才行？有参考的测试电路图吗

**Comment by XIVN1987** [comment]
> 我编译了CH32V203的工程，编译出来的HEX大小50KB，是不是要用CH32V203F8P6才行？有参考的测试电路图吗

我用的 CH32V203F6P6，，没有问题。。

电路的话我用的这个 https://oshwhub.com/xivn1987/daplink ，这个电路是用 AT32F425F8 画的，不过引脚和 CH32V203F6 完全兼容，，可以直接焊。。
