### ISSUE TITLE
WCH CH32V203 (support crystal-less USB)

### ISSUE THREAD

**Issue by kimstik** [XIVN1987/DAPLink#4]
May you acknowledge that CH32V203 is really supports crystal-less USB mode ?

I will appreciate you you will release binaries for CH32V203F6P6 and CH32V203F8P6

**Comment by XIVN1987** [comment]
CH32V203支持crystal-less USB，，我测试过，，没问题

**Comment by kimstik** [comment]
It's strange that the datasheet doesn't say anything about it.
BTW, do you plan to release binaries?

**Comment by XIVN1987** [comment]
建议安装 MounRiver Studio自己编译下，，很简单。。

**Comment by kimstik** [comment]
compiled - did not work. 
if there was a working binary, then I could make a bisection and determine the location of the problem: the code is wrong or the problem is in the hardware.

Getting a bad experience, beginners may be tempted to blame and not use a suspicious chip.
The working binary is a nice user friendly classic way.

**Comment by kimstik** [comment]
I got CH32V203F6P6 working with 8M quartz on CH32V203F-R0-1v0 board
CH32V203**F8**P6 (on CH32V20xF8-R0-1v0 board no XTAL) cannot enumerate

![image](https://user-images.githubusercontent.com/7290319/228864223-ded5ee87-4581-4e7b-8182-58850374a34e.png)

**Comment by XIVN1987** [comment]
电路的话我用的这个 [https://oshwhub.com/xivn1987/daplink](https://oshwhub.com/xivn1987/daplink) ，这个电路是用 AT32F425F8 画的，不过引脚和 CH32V203F6 完全兼容，，可以直接焊。。

**Comment by kimstik** [comment]
My board is [CH32V203F8_MINI](https://github.com/openwch/ch32v20x/blob/main/EVT/PUB/CH32V20xSCH.pdf) page #6.
Crystal-less board

**Comment by kimstik** [comment]
perhaps issue it that CH32V203F8P6 USB pins are bounded to PA13/14 which is also SWD pins ?
