### ISSUE TITLE
RDDI-DAP error

### ISSUE THREAD

**Issue by Andrealee911** [XIVN1987/DAPLink#5]
使用CH32V305FBP6做的下载器，连接STM32F103开发板，Keil的魔术棒里Debug显示RDDI-DAP error，Reset、Max Clock改了也没法解决，请教下该咋办
PS：V305的工程里面DAP_config.h里面SWCLK和SWDIO口为什么是PB12、13？但我改成PA13、14仍然没有解决上述问题。

**Comment by XIVN1987** [comment]
参考 README，，用最新的电路和代码试试。。
