### ISSUE TITLE
代码中F425引脚和Readme电路图的不一致

### ISSUE THREAD

**Issue by AITCK** [XIVN1987/DAPLink#7]
![image](https://github.com/XIVN1987/DAPLink/assets/32191602/d8b35bbe-9bbf-4214-b2ba-0e59bc992cc4)
![image](https://github.com/XIVN1987/DAPLink/assets/32191602/3294f95b-7d8f-454b-989d-41c76cbc8c97)

**Comment by XIVN1987** [comment]
你这代码是旧的，，今年一月31号改过一次引脚。。

**Comment by AITCK** [comment]
看到了，谢谢
