### ISSUE TITLE
关于 对新stm32单片机的支持问题

### ISSUE THREAD

**Issue by MR-ZJZ** [XIVN1987/DAPLink#8]
at32f425版本的daplink，实测对stm32g431和stm32h743都存在无法识别设计的问题，stm32f1和f4均可，麻烦作者看一下是存在什么问题。

**Comment by XIVN1987** [comment]
你看下这两个帖子有帮助不：
[DAPLink 连接 STM32F411 奇怪现象：接线某个 GND 时连接失败。。](https://whycan.com/t_9933.html)
[Keil 通过 DAPLink 连结 STM32F411 时，不发送 JTAG-to-SWD 序列。。](https://whycan.com/t_9927.html)

**Comment by MR-ZJZ** [comment]
感谢作者，我看一下。

**Comment by MR-ZJZ** [comment]
> 你看下这两个帖子有帮助不： [DAPLink 连接 STM32F411 奇怪现象：接线某个 GND 时连接失败。。](https://whycan.com/t_9933.html) [Keil 通过 DAPLink 连结 STM32F411 时，不发送 JTAG-to-SWD 序列。。](https://whycan.com/t_9927.html)

作者您好，关于您提供的两个贴子我重新试了一下。不知您有测试G4和H7的连接兼容性没有。
前一个帖子：在不改变其他任何条件的基础上跟换stm32f103版本的daolink，可以正常连接，您的f425版本更换多个GND均无法连接
后一个帖子：选择keil debuger后点击settings dap的指示灯会闪烁，但无法识别h743，不知是否表示发送了序列，SWJ默认勾选且不可更改。

**Comment by MR-ZJZ** [comment]
> 你看下这两个帖子有帮助不： [DAPLink 连接 STM32F411 奇怪现象：接线某个 GND 时连接失败。。](https://whycan.com/t_9933.html) [Keil 通过 DAPLink 连结 STM32F411 时，不发送 JTAG-to-SWD 序列。。](https://whycan.com/t_9927.html)

貌似是usb隔离引起的问题，感谢作者的帮助！
