### ISSUE TITLE
使用CH32V203C8T6无法连接STM32G030

### ISSUE THREAD

**Issue by dutong0321** [XIVN1987/DAPLink#9]
您好，大佬，我一直想用CH32V203做一款DAPLINK，感谢大佬实现了我的愿望，不过做成以后有些问题，希望大佬可以协助解决！
1.我使用的是CH32V203C8T6，在编译固件时直接修改CH32V203F6P6改成了CH32V203C8T6，然后就进行了编译，板子的引脚也是按照大佬的进行的，应该C8T6和F6P6可以直接替代吧？
2.现在使用串口完全没问题，设备管理器没有找到DAPLINK，但是在KEIL里面找到了DAPLINK，但是在连接设备的时候，一直都是SWD/JTAG Communication Failure，我确信DAPLINK和G030之间连接正常，SWD和CLK脚也无虚焊，应该不是焊接问题，但是无法连接，看看大佬有没有遇到这种情况，拜谢

**Comment by XIVN1987** [comment]
1、换个目标板试试，，比如 STM32F103、STM32F405
2、用逻辑分析仪抓取 SWD 信号看下

**Comment by dutong0321** [comment]
感谢大佬的帮助，我尝试了M0的STM32F030完全没问题，以前以为目标板的支持是由KEIL提供的，现在才明白原来和LINK也有关系，感谢大佬！
